server:
  port: 9022

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: feedbackApp

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 960199815918-smj1gue7frn98aut820sts5i1m0h49fa.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile