server:
  port: 9022

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: feedbackApp
      auto-index-creation: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 960199815918-smj1gue7frn98aut820sts5i1m0h49fa.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:9022
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect